"""Английские описания блюд для генерации фотографий (Pollinations).

Ключ = slug рецепта. Значение = краткое описание блюда для фото-промпта.
"""
from __future__ import annotations

PROMPTS = {
    # --- базовые (recipes_data) ---
    "omlet-syr-shpinat": "fluffy cheese and spinach omelette",
    "syrniki-bez-sahara": "Russian cottage cheese pancakes syrniki with fresh berries",
    "gf-ovsyanka-yabloko": "oatmeal porridge with apple slices and cinnamon in a bowl",
    "grechka-yaytso": "buckwheat porridge with a fried egg",
    "shakshuka": "shakshuka eggs poached in tomato and pepper sauce in a skillet",
    "tvorozhnaya-zapekanka": "cottage cheese casserole with berries slice",
    "yogurt-yagody-semena": "greek yogurt bowl with berries chia seeds and walnuts",
    "yabloko-arahis": "apple slices with peanut butter",
    "morkov-hummus": "carrot and cucumber sticks with hummus dip",
    "tvorog-yagody": "cottage cheese with fresh berries and chia seeds in a bowl",
    "kuritsa-grechka-brokkoli": "grilled chicken breast with buckwheat and broccoli",
    "indeyka-kinoa-ovoshchi": "turkey fillet with quinoa and roasted vegetables",
    "losos-kinoa-sparzha": "baked salmon with quinoa and asparagus",
    "gf-pasta-bolonieze": "pasta bolognese with rich meat sauce",
    "farshirovannye-pertsy": "stuffed bell peppers with meat and rice in tomato sauce",
    "tako-kuritsa": "chicken tacos on corn tortillas with avocado and lime",
    "kurinyy-sup": "clear chicken soup with vegetables in a bowl",
    "tykvennyy-sup-kuritsa": "creamy pumpkin soup with chicken pieces",
    "chechevichnyy-sup": "lentil soup with vegetables in a bowl",
    "treska-ovoshchi": "baked cod fillet with zucchini cherry tomatoes and asparagus",
    "kurinye-kotlety-pyure": "chicken cutlets with mashed potatoes and broccoli",
    "tefteli-indeyka": "turkey meatballs stewed with zucchini and tomatoes",
    "losos-brokkoli": "baked salmon fillet with steamed broccoli and lemon",
    "omlet-ovoshchi-uzhin": "vegetable omelette with feta cheese",
    "grecheskiy-salat-kuritsa": "greek salad with grilled chicken feta and olives",
    "salat-losos-avokado": "salmon and avocado salad with pumpkin seeds",
    "salat-yaytso-avokado": "egg and avocado salad with fresh greens",
    "chia-puding": "chia pudding with fresh berries in a glass jar",
    "shokoladnyy-tvorozhnyy-mus": "chocolate cottage cheese mousse with berries in a cup",
    "zapechennoe-yabloko": "baked apple stuffed with cottage cheese and walnuts",
    "mindalnyy-keks": "almond flour cake with berries slice",
    "kapuchino": "cappuccino coffee with latte art in a cup",
    "kakao-bez-sahara": "hot cocoa drink in a mug",
    "gf-pizza-kuritsa": "pizza with chicken and cherry tomatoes",
    "kartofelnye-chipsy": "homemade baked potato chips with paprika",
    "gf-burger": "beef burger with lettuce tomato and cheese",
    # --- расширенные (recipes_extra) ---
    "yaichnica-avokado-tost": "fried eggs with avocado on toast",
    "omlet-griby-syr": "mushroom and cheese omelette",
    "smuzi-bowl": "berry smoothie bowl with banana chia and coconut",
    "tvorozhnye-pankeyki": "cottage cheese pancakes stack with berries",
    "granola-yogurt": "homemade granola with yogurt and nuts in a bowl",
    "kuritsa-teriyaki": "teriyaki chicken with rice broccoli and sesame",
    "stir-fry-krevetki": "shrimp stir fry with vegetables and rice",
    "risovaya-lapsha-kuritsa": "rice noodles with chicken and vegetables",
    "tykvennoe-karri-nut": "pumpkin and chickpea curry with coconut milk",
    "chili-kon-karne": "chili con carne with beans in a bowl",
    "fahitas-kuritsa": "chicken fajitas with peppers on corn tortillas",
    "rizotto-griby": "creamy mushroom risotto",
    "kuritsa-pikkata": "chicken piccata with lemon capers and asparagus",
    "forel-ovoshchi-par": "steamed trout fillet with vegetables",
    "skumbriya-zapechennaya": "baked mackerel with vegetables and lemon",
    "krevetki-gril-salat": "grilled shrimp with fresh green salad and avocado",
    "befstroganov-grechka": "beef stroganoff with buckwheat",
    "kurinyy-zhulien": "chicken julienne with mushrooms in creamy cheese sauce",
    "baklazhany-farsh-syr": "baked eggplant with minced meat and melted mozzarella",
    "oladi-kabachki": "zucchini fritters with yogurt dip",
    "krem-sup-shampinyony": "creamy mushroom soup",
    "uha": "russian fish soup with cod and vegetables",
    "tom-yam-krevetki": "tom yum soup with shrimp and coconut milk",
    "tsezar-kuritsa": "caesar salad with grilled chicken",
    "tabule-kinoa": "quinoa tabbouleh salad with tomatoes cucumber and herbs",
    "salat-tunec-fasol": "tuna and bean salad with vegetables",
    "salat-svekla-feta": "roasted beetroot salad with feta and walnuts",
    "panna-kotta": "panna cotta dessert with berry topping",
    "tykvennye-maffiny": "almond flour pumpkin muffins",
    "yogurtovoe-morozhenoe": "frozen yogurt with fresh berries",
    "zelenyy-smuzi": "green smoothie with spinach apple and cucumber in a glass",
    "matcha-latte": "matcha latte with foam in a cup",
    "gf-naggetsy": "golden baked chicken nuggets",
    "kartofelnye-dolki": "roasted potato wedges with herbs",
    # --- второе расширение (recipes_extra2) ---
    "frittata-ovoshchi": "vegetable frittata with cheese",
    "kinoa-kasha": "quinoa porridge with berries and cinnamon in a bowl",
    "yaichnica-losos": "scrambled eggs with salmon pieces and dill",
    "ovsyanoblin-tvorog": "oatmeal crepe filled with cottage cheese and berries",
    "plov-kuritsa": "chicken plov rice pilaf with carrots",
    "gulyash": "beef goulash stew with peppers",
    "kuritsa-karri-ris": "chicken curry with rice",
    "kish-ovoshchi": "vegetable quiche slice",
    "lazanya-baklazhan": "eggplant lasagna with meat and melted cheese",
    "kurinyy-shnitsel": "golden chicken schnitzel",
    "burrito-bowl": "burrito bowl with chicken rice beans and avocado",
    "stejk-ovoshchi-gril": "grilled beef steak with grilled vegetables",
    "kurinye-shashlychki": "chicken skewers with peppers and zucchini",
    "sibas-zapechennyy": "baked sea bass fillet with asparagus and cherry tomatoes",
    "frikadelki-tomat": "meatballs in tomato sauce",
    "zapekanka-cvetnaya": "cauliflower and chicken cheese casserole",
    "ovoshchnoe-ragu-nut": "vegetable stew with chickpeas",
    "nisuaz": "nicoise salad with tuna egg and green beans",
    "kapreze": "caprese salad with mozzarella tomatoes and basil",
    "teplyy-salat-ovoshchi": "warm salad with roasted vegetables and chicken",
    "salat-krevetki-kinoa": "shrimp and quinoa salad with avocado",
    "gaspacho": "cold gazpacho tomato soup in a bowl",
    "sup-frikadelki": "chicken meatball soup with vegetables",
    "sup-cvetnaya-kapusta": "creamy cauliflower soup",
    "syrnye-palochki": "baked cheese sticks",
    "guakamole-ovoshchi": "guacamole with vegetable sticks",
    "yaichnye-maffiny": "egg muffins with vegetables",
    "chizkeyk-bez-sahara": "cheesecake slice with berries",
    "brauni-mindal": "chocolate brownie squares",
    "banan-nice-cream": "banana nice cream with cocoa",
    "imbirnyy-chay": "ginger tea with lemon in a glass",
    "yagodnyy-mors": "berry drink in a glass",
    "kesadilya": "chicken quesadilla wedges with melted cheese",
    "kurinye-krylya": "baked chicken wings",
}
